### ISSUE TITLE
Телепорт Всех Игроков.

### ISSUE THREAD

**Issue by QuiX43** [goodwinxp/Yorozuya#105]
Можно ли сделать гм-команду на телепорт всех онлайн игроков к гму?

**Comment by goodwinxp** [comment]
Можно, регистрируете свою гм команду так же как это делают корейцы и реализуете функционал.
Если это будет интересно больше чем 10 людям, то я сам это сделаю
Собственно "голосовать" можно вот так:
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by Zef201** [comment]
Можешь ещё сделать 2 команды
1. Телепортировать 1 игрока к себе
2. Tелепортироваться к игроку

**Comment by goodwinxp** [comment]
@Zef201 эти команды уже есть в оригинале
1. charcall
2. gotochar
