### ISSUE TITLE
Авто выдача наград

### ISSUE THREAD

**Issue by fortuner92** [goodwinxp/Yorozuya#108]
Модуль наград игроков, гильдий, расс, за выполнение простейших требований.
Например: 
быть онлайн 1+час в игре
накопить за 1 час +1000 очков охоты
убить боса и вся раса получит плюшки

много чего можно придумать.

**Comment by goodwinxp** [comment]
Смотри сюда
https://github.com/goodwinxp/Yorozuya/issues/55
