### ISSUE TITLE
Модуль защиты и окон

### ISSUE THREAD

**Issue by fortuner92** [goodwinxp/Yorozuya#110]
Добавить модуль ограничения входа с ip, номера сетевой карты и пароля.
с 1 ip
с 1 сетевой
с помощью пароля.

Смотря насколько это возможно без модификации клиента.
Хотя бы ограничение по ip, паролю.
Например заходит игрок на персонажа и для любых дальнейших действий нужно снять блокировку.
Написал пароль в специальный чат и блокировка снята.

**Comment by goodwinxp** [comment]
1. Относительно 1 клиент = 1 ip. Так делать нельзя в виду того что есть игроки у которых нет белого ipv4 и они сидят с одной сети => только 1 сможет играть
2. Относительно MAC адреса клиента - не целесообразно, подменить его дело 5 минут
3. Относительно пароля - не целесообразно, и требует доработки личных кабинетов
4. Ограничивать вход должен логин сервер, а не игровой сервер
