### ISSUE TITLE
Модуль голосование за патра

### ISSUE THREAD

**Issue by Harvey89** [goodwinxp/Yorozuya#122]
goodwinxp, можешь сюда добавить https://a.radikal.ru/a24/1801/d1/a1728311529b.png голосование игроков за патра

Например:
Доступный уровень для голосования = 50
Необходимое количество ОС, для успешного голосования = 50000 (ну или далант/pvp)
Необходимое количество времени, для успешного голосования = 30 минут

**Comment by goodwinxp** [comment]
это уже всё есть, причём именно в этом конфиге откуда скрин

**Comment by Harvey89** [comment]
goodwinxp, можешь описание сделать к этому модулю ?

**Comment by goodwinxp** [comment]
@Harvey89 ок, добавлю на след. неделе, раз конфига не достаточно
