### ISSUE TITLE
Баги?

### ISSUE THREAD

**Issue by fortuner92** [goodwinxp/Yorozuya#127]
Просьба не закидывать тапками.
Заглянул на сайты защит в логи исправлений. и нашел следующие строчки:

С девкорпа 2232
Исправлено: Отображение заточки выбранной цели.

С церберус систем 2232
Фикс использования скилов магистра
Дополнительная проверка должности при ношении шмота ГЛ или офицера(если должности нет то статы от шмота не работают даже если их не снимать).
Фикс накрутки урона через патроны
Фикс одевания осадок в слоты патронов
Фикс падения сервера при переполнеии слота батарей персональной буровой установки.
Фикс алгоритма призыва\телепортации персонажей(утечка памяти приводившая к полному отказу в работе допингов и умений призыва). А так же дюп предметов через эту ошибку.

А тут есть или планируются данные фиксы?

**Comment by goodwinxp** [comment]
Отображение заточки, нельзя пофиксить на корню не сломав свечение вещей при заточке.
На счёт магистра - это выключается через скрипты, фикс для лентяев
На счёт остального, сначала тестируете, потом создаёте issue с полным описанием, бегать и выяснять я не буду. 
И да, тут исправлен краш через батареи, накрутка урона через патроны
Остальное я в душе не чаю как воспроизводить
