### ISSUE TITLE
Очки Охоты

### ISSUE THREAD

**Issue by Acharnes** [goodwinxp/Yorozuya#76]
Вроде как после выхода 2232 обновления, корейцы вырезали функцию обновления очков охоты, и сейчас получается так что если бить мобов очки идут но в окне не обновляются, если в магазине продать любой товар за платину, ср или другие очки - то очки охоты сразу обновляются, вообще отображение только через продажу.

**Comment by goodwinxp** [comment]
https://github.com/goodwinxp/Yorozuya/commit/97e86139ff6ebd2b7ee39335680a6c00bba1d277

**Comment by goodwinxp** [comment]
Со стороны сервера полноценный фикс не возможен в виду полного игнорирования обновления ОО со стороны клиента
